[package]
edition.workspace = true
name = "source_generator"
publish = false
license.workspace = true
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
file_type = { path = "../../file_type", version = "0.8.8" }
tracing = { workspace = true }
