[package]
edition.workspace = true
name = "source_generator"
publish = false
license.workspace = true
version.workspace = true

[dependencies]
file_type = { path = "../../file_type", version = "0.5.3" }
