use crate::format::{
    ByteSequence, FileFormat, InternalSignature, PositionType, Regex, RelatedFormat,
    RelationshipType, SourceType, Token,
};

pub(crate) const PRONOM_2020: FileFormat = FileFormat {
    id: 2_020,
    source_type: SourceType::Pronom,
    name: "Wavefront OBJ File",
    extensions: &["obj"],
    media_types: &[],
    internal_signatures: &[InternalSignature {
        byte_sequences: &[ByteSequence {
            position_type: PositionType::BOF,
            offset: Some(0),
            regex: Regex {
                tokens: &[
                    Token::Literal(&[0x76, 0x20]),
                    Token::WildcardCountRange(0, 8),
                    Token::Range(&[0x30], &[0x39]),
                    Token::Literal(&[0x2E]),
                    Token::Range(&[0x30], &[0x39]),
                    Token::WildcardCountRange(0, 32),
                    Token::Literal(&[0x20]),
                    Token::WildcardCountRange(0, 8),
                    Token::Range(&[0x30], &[0x39]),
                    Token::Literal(&[0x2E]),
                    Token::Range(&[0x30], &[0x39]),
                    Token::WildcardCountRange(0, 32),
                    Token::Literal(&[0x20]),
                    Token::WildcardCountRange(0, 8),
                    Token::Range(&[0x30], &[0x39]),
                    Token::Literal(&[0x2E]),
                    Token::Range(&[0x30], &[0x39]),
                    Token::WildcardCountRange(0, 64),
                    Token::Literal(&[0x0A]),
                    Token::AnyWildcard,
                    Token::Literal(&[0x66, 0x20]),
                    Token::WildcardCountRange(0, 1),
                    Token::Range(&[0x31], &[0x39]),
                    Token::WildcardCountRange(0, 20),
                    Token::Literal(&[0x20]),
                    Token::WildcardCountRange(0, 1),
                    Token::Range(&[0x31], &[0x39]),
                    Token::WildcardCountRange(0, 20),
                    Token::Literal(&[0x20]),
                    Token::WildcardCountRange(0, 1),
                    Token::Range(&[0x31], &[0x39]),
                    Token::WildcardCountRange(0, 40),
                    Token::Literal(&[0x0A]),
                ],
            },
        }],
    }],
    related_formats: &[],
};
