use crate::format::{ByteSequence, FileFormat, PositionType, Regex, Signature, SourceType, Token};
use crate::FileType;

pub(crate) const PRONOM_1154: FileType = FileType {
    file_format: &FileFormat {
        id: 1_154,
        source_type: SourceType::Pronom,
        name: "Portable Grey Map - Binary",
        extensions: &["pgmb", "pgm"],
        media_types: &[],
        signatures: &[
            Signature {
                byte_sequences: &[ByteSequence {
                    position_type: PositionType::BOF,
                    offset: Some(0),
                    regex: Regex {
                        tokens: &[
                            Token::Literal(&[0x50, 0x35]),
                            Token::Any(&[
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0D])],
                                &[Token::Literal(&[0x0A])],
                            ]),
                            Token::WildcardCountRange(0, 2),
                            Token::Literal(&[0x23]),
                            Token::WildcardCountRange(0, 70),
                            Token::Literal(&[0x0A]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                        ],
                    },
                }],
            },
            Signature {
                byte_sequences: &[ByteSequence {
                    position_type: PositionType::BOF,
                    offset: Some(0),
                    regex: Regex {
                        tokens: &[
                            Token::Literal(&[0x50, 0x35]),
                            Token::Any(&[
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0D])],
                                &[Token::Literal(&[0x0A])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                            Token::Any(&[
                                &[Token::Literal(&[0x30])],
                                &[Token::Literal(&[0x31])],
                                &[Token::Literal(&[0x32])],
                                &[Token::Literal(&[0x33])],
                                &[Token::Literal(&[0x34])],
                                &[Token::Literal(&[0x35])],
                                &[Token::Literal(&[0x36])],
                                &[Token::Literal(&[0x37])],
                                &[Token::Literal(&[0x38])],
                                &[Token::Literal(&[0x39])],
                                &[Token::Literal(&[0x20])],
                                &[Token::Literal(&[0x0A])],
                                &[Token::Literal(&[0x0D])],
                            ]),
                        ],
                    },
                }],
            },
        ],
        related_formats: &[],
    },
};
