use crate::format::{ByteSequence, FileFormat, InternalSignature, PositionType, Regex, Token};

pub(crate) const WIKIDATA_105857083: FileFormat = FileFormat {
    id: 105_857_083,
    puid: "wikidata/105857083",
    name: "G-code (generated by Cura)",
    extensions: &["gcode"],
    media_types: &["text/plain"],
    internal_signatures: &[],
    related_formats: &[],
};
