use crate::FileType;
use crate::format::{ByteSequence, FileFormat, PositionType, Regex, Signature, SourceType, Token};

pub(crate) const WIKIDATA_105857012: FileType = FileType {
    file_format: &FileFormat {
        id: 105_857_012,
        source_type: SourceType::Wikidata,
        name: "G-code (generated by Simplify3D)",
        extensions: &["gcode"],
        media_types: &["text/plain"],
        signatures: &[Signature {
            byte_sequences: &[ByteSequence {
                position_type: PositionType::BOF,
                offset: Some(0),
                regex: Regex {
                    tokens: &[Token::Literal(&[
                        0x3B, 0x20, 0x47, 0x2D, 0x43, 0x6F, 0x64, 0x65, 0x20, 0x67, 0x65, 0x6E,
                        0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x20, 0x62, 0x79, 0x20, 0x53, 0x69,
                        0x6D, 0x70, 0x6C, 0x69, 0x66, 0x79, 0x33, 0x44, 0x28, 0x52, 0x29, 0x20,
                        0x56, 0x65, 0x72, 0x73, 0x69, 0x6F, 0x6E, 0x20,
                    ])],
                },
            }],
        }],
        related_formats: &[],
    },
};
