use crate::format::{ByteSequence, FileFormat, PositionType, Regex, Signature, SourceType, Token};

pub(crate) const WIKIDATA_105856887: FileFormat = FileFormat {
    id: 105_856_887,
    source_type: SourceType::Wikidata,
    name: "G-code (generated by KISSSlicer)",
    extensions: &["gcode"],
    media_types: &["text/plain"],
    signatures: &[Signature {
        byte_sequences: &[ByteSequence {
            position_type: PositionType::BOF,
            offset: Some(0),
            regex: Regex {
                tokens: &[Token::Literal(&[
                    0x3B, 0x20, 0x4B, 0x49, 0x53, 0x53, 0x6C, 0x69, 0x63, 0x65, 0x72, 0x20, 0x2D,
                    0x20,
                ])],
            },
        }],
    }],
    related_formats: &[],
};
