use crate::format::{
    ByteSequence, FileFormat, InternalSignature, PositionType, Regex, SourceType, Token,
};

pub(crate) const WIKIDATA_105857089: FileFormat = FileFormat {
    id: 105_857_089,
    source_type: SourceType::Wikidata,
    name: "G-code (generated by Meshy)",
    extensions: &["gcode"],
    media_types: &["text/plain"],
    internal_signatures: &[InternalSignature {
        byte_sequences: &[ByteSequence {
            position_type: PositionType::BOF,
            offset: Some(0),
            regex: Regex {
                tokens: &[Token::Literal(&[
                    0x3B, 0x20, 0x46, 0x49, 0x4C, 0x45, 0x4E, 0x41, 0x4D, 0x45, 0x3A, 0x20,
                ])],
            },
        }],
    }],
    related_formats: &[],
};
