use crate::FileType;
use crate::format::{ByteSequence, FileFormat, PositionType, Regex, Signature, SourceType, Token};

pub(crate) const WIKIDATA_105857089: FileType = FileType {
    file_format: &FileFormat {
        id: 105_857_089,
        source_type: SourceType::Wikidata,
        name: "G-code (generated by Meshy)",
        extensions: &["gcode"],
        media_types: &["text/plain"],
        signatures: &[Signature {
            byte_sequences: &[ByteSequence {
                position_type: PositionType::BOF,
                offset: Some(0),
                regex: Regex {
                    tokens: &[Token::Literal(&[
                        0x3B, 0x20, 0x46, 0x49, 0x4C, 0x45, 0x4E, 0x41, 0x4D, 0x45, 0x3A, 0x20,
                    ])],
                },
            }],
        }],
        related_formats: &[],
    },
};
