use crate::format::{ByteSequence, FileFormat, InternalSignature, PositionType, Regex, Token};

pub(crate) const WIKIDATA_1767050: FileFormat = FileFormat {
    id: 1_767_050,
    puid: "wikidata/1767050",
    name: "OpenOffice.org XML",
    extensions: &[
        "stc", "stc", "stc", "stc", "stc", "stc", "stc", "stc", "stc", "stc", "std", "std", "std",
        "std", "std", "std", "std", "std", "std", "std", "sti", "sti", "sti", "sti", "sti", "sti",
        "sti", "sti", "sti", "sti", "stw", "stw", "stw", "stw", "stw", "stw", "stw", "stw", "stw",
        "stw", "sxc", "sxc", "sxc", "sxc", "sxc", "sxc", "sxc", "sxc", "sxc", "sxc", "sxd", "sxd",
        "sxd", "sxd", "sxd", "sxd", "sxd", "sxd", "sxd", "sxd", "sxg", "sxg", "sxg", "sxg", "sxg",
        "sxg", "sxg", "sxg", "sxg", "sxg", "sxi", "sxi", "sxi", "sxi", "sxi", "sxi", "sxi", "sxi",
        "sxi", "sxi", "sxm", "sxm", "sxm", "sxm", "sxm", "sxm", "sxm", "sxm", "sxm", "sxm", "sxw",
        "sxw", "sxw", "sxw", "sxw", "sxw", "sxw", "sxw", "sxw", "sxw",
    ],
    media_types: &[
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.calc.template",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.draw.template",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.impress.template",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.math",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.sun.xml.writer.template",
    ],
    internal_signatures: &[],
    related_formats: &[],
};
