use crate::format::{ByteSequence, FileFormat, InternalSignature, PositionType, Regex, Token};

pub(crate) const WIKIDATA_336284: FileFormat = FileFormat {
    id: 336_284,
    puid: "wikidata/336284",
    name: "MPEG-1",
    extensions: &[
        "m1a", "m1a", "m1a", "m1a", "m1v", "m1v", "m1v", "m1v", "m2a", "m2a", "m2a", "m2a", "mp1",
        "mp1", "mp1", "mp1", "mp2", "mp2", "mp2", "mp2", "mp3", "mp3", "mp3", "mp3", "mpa", "mpa",
        "mpa", "mpa", "mpeg", "mpeg", "mpeg", "mpeg", "mpg", "mpg", "mpg", "mpg", "mpv", "mpv",
        "mpv", "mpv",
    ],
    media_types: &[
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "audio/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
        "video/mpeg",
    ],
    internal_signatures: &[],
    related_formats: &[],
};
