use crate::format::{FileFormat, SourceType};

pub(crate) const LINGUIST_183: FileFormat = FileFormat {
    id: 183,
    source_type: SourceType::Linguist,
    name: "JavaScript",
    extensions: &[
        "_js",
        "bones",
        "cjs",
        "es",
        "es6",
        "frag",
        "gs",
        "jake",
        "javascript",
        "js",
        "jsb",
        "jscad",
        "jsfl",
        "jslib",
        "jsm",
        "jspre",
        "jss",
        "jsx",
        "mjs",
        "njs",
        "pac",
        "sjs",
        "ssjs",
        "xsjs",
        "xsjslib",
    ],
    media_types: &["text/javascript"],
    signatures: &[],
    related_formats: &[],
};
