use crate::FileType;
use crate::format::{FileFormat, SourceType};

pub(crate) const LINGUIST_399: FileType = FileType {
    file_format: &FileFormat {
        id: 399,
        source_type: SourceType::Linguist,
        name: "XML",
        extensions: &[
            "adml",
            "admx",
            "ant",
            "axaml",
            "axml",
            "builds",
            "ccproj",
            "ccxml",
            "clixml",
            "cproject",
            "cscfg",
            "csdef",
            "csl",
            "csproj",
            "ct",
            "depproj",
            "dita",
            "ditamap",
            "ditaval",
            "dll.config",
            "dotsettings",
            "filters",
            "fsproj",
            "fxml",
            "glade",
            "gml",
            "gmx",
            "gpx",
            "grxml",
            "gst",
            "hzp",
            "iml",
            "ivy",
            "jelly",
            "jsproj",
            "kml",
            "launch",
            "mdpolicy",
            "mjml",
            "mm",
            "mod",
            "mojo",
            "mxml",
            "natvis",
            "ncl",
            "ndproj",
            "nproj",
            "nuspec",
            "odd",
            "osm",
            "pkgproj",
            "pluginspec",
            "proj",
            "props",
            "ps1xml",
            "psc1",
            "pt",
            "qhelp",
            "rdf",
            "res",
            "resx",
            "rs",
            "rss",
            "sch",
            "scxml",
            "sfproj",
            "shproj",
            "srdf",
            "storyboard",
            "sublime-snippet",
            "sw",
            "targets",
            "tml",
            "ts",
            "tsx",
            "typ",
            "ui",
            "urdf",
            "ux",
            "vbproj",
            "vcxproj",
            "vsixmanifest",
            "vssettings",
            "vstemplate",
            "vxml",
            "wixproj",
            "workflow",
            "wsdl",
            "wsf",
            "wxi",
            "wxl",
            "wxs",
            "x3d",
            "xacro",
            "xaml",
            "xib",
            "xlf",
            "xliff",
            "xmi",
            "xml",
            "xml.dist",
            "xmp",
            "xproj",
            "xsd",
            "xspec",
            "xul",
            "zcml",
        ],
        media_types: &["text/xml"],
        signatures: &[],
        related_formats: &[],
    },
};
