use crate::format::FileFormat;

pub(crate) const LINGUIST_326: FileFormat = FileFormat {
    id: 326,
    puid: "linguist/326",
    name: "Ruby",
    extensions: &[
        "builder",
        "eye",
        "fcgi",
        "gemspec",
        "god",
        "jbuilder",
        "mspec",
        "pluginspec",
        "podspec",
        "prawn",
        "rabl",
        "rake",
        "rb",
        "rbi",
        "rbuild",
        "rbw",
        "rbx",
        "ru",
        "ruby",
        "spec",
        "thor",
        "watchr",
    ],
    media_types: &["text/x-ruby"],
    internal_signatures: &[],
    related_formats: &[],
};
