name: fuzz

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 12 * * 0'

permissions:
  contents: read

jobs:
  fuzz:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    env:
      RUSTUP_TOOLCHAIN: nightly
    strategy:
      fail-fast: false
      matrix:
        target:
          - file_type_bytes
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo fuzz
        run: cargo install cargo-fuzz
      - name: Fuzz Tests
        run: cargo fuzz run ${{ matrix.target }} -- -max_total_time=120 -rss_limit_mb=8192 ${{ matrix.option }}
