name: Pull request labeler

on:
  pull_request_target:
    types: [ opened, edited ]

permissions:
  contents: read

jobs:
  main:
    name: PR Labeler
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Label pull request
        uses: release-drafter/release-drafter@v6
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
