name: Update draft releases

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      # Latest commit to include with the release. If omitted, use the latest commit on the main branch.
      sha:
        description: Commit SHA
        type: string

permissions:
  contents: read
  pull-requests: read

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Draft release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          commitish: ${{ inputs.sha || github.sha }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
